CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL,
    hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    state INTEGER DEFAULT 0 NOT NULL,
    week INTEGER DEFAULT 1 NOT NULL,
    date TEXT,
    FOREIGN KEY(user_id) REFERENCES users(id)
);
